
'use strict';
// Public configuration contains repository coordinates only. Never put a token here.
const $ = id => document.getElementById(id);
const icon = name => `<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const EMPTY = {version:1,teamName:'퇴마사',leaderId:null,updatedAt:null,members:[]};
const LIMIT = 900000, POLL_MS = 30000;
let state=structuredClone(EMPTY), session=null, editingId=null, view='grid', busy=false, polling=false, pendingDraft=null, formSnapshot='', lastCheck=null, syncError='', pollAfter=0, epoch=0, lastIssue='', confirmResolver=null;
const requests=new Set();
const config=Object.assign({owner:'',repo:'',branch:'main',path:'data/team.json'},window.ARCHIVE_CONFIG||{});
function text(value,max,label,required=false){if(typeof value!=='string'||value.length>max||(required&&!value.trim()))throw new Error(label+' 형식이 올바르지 않아요.');return value.trim();}
function numberText(value,min,max,label){if(value===undefined||value===null||value==='')return '';const s=String(value);if(!/^\d+$/.test(s)||Number(s)<min||Number(s)>max)throw new Error(label+' 범위를 확인해 주세요.');return s;}
function validate(data){
 if(!data||data.version!==1||!Array.isArray(data.members)||data.members.length>300)throw new Error('지원하는 팀 기록 형식(version 1)이 아니거나 팀원이 300명을 초과했어요.');
 const teamName=text(data.teamName,30,'팀명',true),ids=new Set();
 const members=data.members.map(m=>{if(!m||typeof m!=='object')throw new Error('팀원 정보가 올바르지 않아요.');const id=text(m.id,100,'기록 ID',true);if(ids.has(id))throw new Error('중복된 팀원 기록이 있어요.');ids.add(id);if(!Array.isArray(m.abilities)||m.abilities.length>12)throw new Error('능력은 팀원마다 12개까지 가능해요.');const gender=text(m.gender??'',10,'성별');if(!['','여자','남자','기타','비공개'].includes(gender))throw new Error('성별 선택값을 확인해 주세요.');return{id,name:text(m.name,30,'이름',true),gender,age:numberText(m.age,1,120,'나이'),birthYear:numberText(m.birthYear,1900,2100,'출생 연도'),school:text(m.school??'',70,'학교'),grade:numberText(m.grade,1,12,'학년'),classroom:text(m.classroom??'',15,'반'),position:text(m.position??'',40,'역할'),abilities:[...new Set(m.abilities.map(a=>text(a,30,'능력',true)))],address:text(m.address??'',200,'주소'),memo:text(m.memo??'',1500,'메모'),createdAt:typeof m.createdAt==='string'&&Number.isFinite(Date.parse(m.createdAt))?new Date(m.createdAt).toISOString():new Date().toISOString()};});
 if(members.length&&(!data.leaderId||!ids.has(data.leaderId)))throw new Error('팀장으로 지정된 팀원의 기록을 찾을 수 없어요.');if(!members.length&&data.leaderId!==null)throw new Error('팀원이 없는 기록은 팀장을 지정할 수 없어요.');
 return{version:1,teamName,leaderId:members.length?data.leaderId:null,members,updatedAt:typeof data.updatedAt==='string'&&Number.isFinite(Date.parse(data.updatedAt))?new Date(data.updatedAt).toISOString():null};
}
function toast(message,error=false){const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;$('toasts').append(el);while($('toasts').children.length>2)$('toasts').firstElementChild.remove();setTimeout(()=>el.remove(),error?9000:4000);}
function connection(){const c={owner:$('repoOwner').value.trim(),repo:$('repoName').value.trim(),branch:$('repoBranch').value.trim(),path:$('repoPath').value.trim()};if(!/^[A-Za-z0-9][A-Za-z0-9-]{0,99}$/.test(c.owner)||!/^[A-Za-z0-9_.-]{1,100}$/.test(c.repo)||c.repo==='.'||c.repo==='..')throw new Error('저장소 소유자와 이름을 확인해 주세요. URL 전체가 아닌 이름만 입력해요.');if(!c.branch||c.branch.length>150||/[\s?#\\]/.test(c.branch)||c.branch.includes('..'))throw new Error('올바른 브랜치 이름을 입력해 주세요.');if(!c.path.endsWith('.json')||c.path.startsWith('/')||c.path.split('/').some(s=>!s||s==='.'||s==='..')||/[\x00-\x1f?#\\]/.test(c.path)||c.path.length>200)throw new Error('기록 경로는 data/team.json처럼 저장소 안의 JSON 파일 경로여야 해요.');return c;}
function base(c=session?.config){return '/repos/'+encodeURIComponent(c.owner)+'/'+encodeURIComponent(c.repo);}
function contentsPath(c=session?.config){return base(c)+'/contents/'+c.path.split('/').map(encodeURIComponent).join('/');}
function githubUrl(){const c=session.config;return 'https://github.com/'+encodeURIComponent(c.owner)+'/'+encodeURIComponent(c.repo)+'/blob/'+encodeURIComponent(c.branch)+'/'+c.path.split('/').map(encodeURIComponent).join('/');}
function explain(error){if(error.status===401)return '접근 토큰이 만료되었거나 올바르지 않아요. 새 토큰으로 다시 연결해 주세요.';if(error.status===403||error.status===429){if(error.rateLimited)return 'GitHub API 호출 제한에 도달했어요. 잠시 기다린 뒤 다시 시도해 주세요.';return '접근 권한이 부족해요. 저장소 권한, 토큰의 Contents 권한, 조직의 토큰 승인 상태와 브랜치 보호 규칙을 확인해 주세요.';}if(error.status===404)return '저장소·브랜치·파일을 찾을 수 없거나 접근 권한이 없어요. 설정과 저장소 초대 수락, 토큰의 저장소 선택을 확인해 주세요.';if(error.status===409||error.status===422)return '친구가 먼저 저장했거나 GitHub가 변경을 거절했어요. 최신 기록을 불러온 뒤 다시 적용해 주세요. 반복되면 브랜치 보호 규칙도 확인해 주세요.';if(error.name==='AbortError')return '요청이 취소되거나 응답 시간이 초과됐어요. 저장 요청이었다면 GitHub에 반영됐을 수도 있으니 최신 기록을 확인해 주세요.';if(error instanceof TypeError)return 'GitHub에 연결하지 못했어요. 인터넷 연결을 확인해 주세요. 저장 요청이었다면 최신 기록을 확인한 후 다시 시도해 주세요.';return error.message||'요청을 완료하지 못했어요.';}
async function api(path,options={},auth=session){if(!auth)throw new Error('먼저 기록실에 연결해 주세요.');if(!path.startsWith('/repos/')&&path!=='/user')throw new Error('지원하지 않는 API 경로예요.');const controller=new AbortController();requests.add(controller);const timeout=setTimeout(()=>controller.abort(),20000);try{const response=await fetch('https://api.github.com'+path,{method:options.method||'GET',headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:'Bearer '+auth.token,...(options.body?{'Content-Type':'application/json'}:{})},body:options.body?JSON.stringify(options.body):undefined,cache:'no-store',credentials:'omit',redirect:'error',referrerPolicy:'no-referrer',signal:controller.signal});if(!response.ok){const error=new Error('GitHub 응답 오류');error.status=response.status;error.rateLimited=response.status===429||response.headers.get('x-ratelimit-remaining')==='0'||Boolean(response.headers.get('retry-after'));const seconds=Number(response.headers.get('retry-after'));if(error.rateLimited)pollAfter=Date.now()+(Number.isFinite(seconds)&&seconds>0?seconds*1000:120000);throw error;}return await response.json();}finally{clearTimeout(timeout);requests.delete(controller);}}
function encodeJson(data){const bytes=new TextEncoder().encode(JSON.stringify(data,null,2)+'\n');if(bytes.length>LIMIT)throw new Error('기록 파일이 너무 커요. 900KB 이하로 줄여 주세요.');let bin='';for(let i=0;i<bytes.length;i+=8192)bin+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(bin);}
async function readRemote(auth=session){const c=auth.config;const info=await api(base(c),{},auth);if(!info.private)throw new Error('기록 저장소가 공개되어 있어요. 비공개로 변경한 뒤 다시 연결해 주세요.');const file=await api(contentsPath(c)+'?ref='+encodeURIComponent(c.branch)+'&_='+Date.now(),{},auth);if(file.type!=='file'||file.encoding!=='base64'||!file.sha||typeof file.content!=='string'||file.size>LIMIT)throw new Error('기록은 900KB 이하의 일반 JSON 파일이어야 해요.');let raw;try{raw=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(atob(file.content.replace(/\s/g,'')),x=>x.charCodeAt(0))));}catch(e){throw new Error('GitHub 기록 파일의 JSON을 읽지 못했어요. 기존 파일은 덮어쓰지 않았어요. 파일 내용을 확인해 주세요.');}return{state:validate(raw),sha:file.sha};}
function updateSaveStatus(){const label=busy?'GitHub에 저장 중…':pendingDraft?'미저장 변경 있음':syncError?'최신 확인 필요':lastCheck?'GitHub 연결됨':'연결 확인 중';$('saveLabel').textContent=label;$('saveState').classList.toggle('dirty',Boolean(pendingDraft||syncError));$('saveState').title=pendingDraft?'저장되지 않은 변경 보기':syncError||('최근 확인: '+(lastCheck?new Date(lastCheck).toLocaleTimeString('ko-KR'):'없음'));}
function setBusy(value){busy=value;document.body.classList.toggle('busy-overlay',value);document.querySelectorAll('button').forEach(b=>{if(value){b.dataset.wasDisabled=String(b.disabled);b.disabled=true;}else if('wasDisabled'in b.dataset){b.disabled=b.dataset.wasDisabled==='true';delete b.dataset.wasDisabled;}});document.querySelectorAll('dialog input,dialog textarea,dialog select,#loginForm input').forEach(el=>{if(value){el.dataset.wasDisabled=String(el.disabled);el.disabled=true;}else if('wasDisabled'in el.dataset){el.disabled=el.dataset.wasDisabled==='true';delete el.dataset.wasDisabled;}});updateSaveStatus();}
function confirmAction(title,message,label='확인',danger=false){return new Promise(resolve=>{if(confirmResolver){resolve(false);return;}const d=$('confirmDialog');$('confirmTitle').textContent=title;$('confirmMessage').textContent=message;$('confirmOkay').textContent=label;$('confirmOkay').className='btn '+(danger?'btn-danger':'btn-primary');confirmResolver=resolve;d.showModal();$('confirmCancel').focus();});}
function finishConfirm(accepted){const resolve=confirmResolver;confirmResolver=null;$('confirmDialog').close();if(resolve)resolve(accepted);}
$('confirmOkay').onclick=()=>finishConfirm(true);$('confirmCancel').onclick=()=>finishConfirm(false);$('confirmClose').onclick=()=>finishConfirm(false);$('confirmDialog').addEventListener('cancel',e=>{e.preventDefault();if(!busy)finishConfirm(false);});
function showIssue(message=lastIssue){lastIssue=message||'저장하지 않은 변경사항이 있어요.';$('issueMessage').textContent=lastIssue;if(!$('issueDialog').open)$('issueDialog').showModal();}
function contentSignature(data){return JSON.stringify({...data,updatedAt:null});}
async function commit(candidate,message='Update team archive'){
 if(!session||busy)return false;
 let next;try{next=validate(candidate);encodeJson(next);}catch(e){toast(explain(e),true);return false;}
 if(pendingDraft&&contentSignature(pendingDraft)!==contentSignature(next)){if(!(await confirmAction('이전 미저장 변경이 있어요','새 변경으로 미저장 초안을 바꿀까요? 이전 초안이 필요하면 취소한 뒤 상단 상태 표시에서 파일로 보관해 주세요.','새 변경으로 저장')))return false;}
 next.updatedAt=new Date().toISOString();pendingDraft=next;const auth=session,requestEpoch=epoch;setBusy(true);let success=false,errorMessage='';
 try{const info=await api(base(auth.config),{},auth);if(!info.private)throw new Error('기록 저장소가 공개되어 있어 저장을 중단했어요. GitHub에서 비공개로 변경해 주세요.');const body={message,content:encodeJson(next),branch:auth.config.branch};if(auth.sha)body.sha=auth.sha;const result=await api(contentsPath(),{method:'PUT',body},auth);if(requestEpoch!==epoch)return false;if(!result.content?.sha)throw new Error('저장 응답을 확인하지 못했어요. 최신 기록을 확인해 주세요.');session.sha=result.content.sha;state=next;pendingDraft=null;syncError='';lastCheck=Date.now();success=true;}
 catch(e){if(requestEpoch===epoch){errorMessage=explain(e);syncError=errorMessage;}}
 finally{setBusy(false);if(requestEpoch===epoch)render();}
 if(errorMessage)showIssue(errorMessage);return success;
}
function shortClass(m){return [m.grade?m.grade+'학년':'',m.classroom?m.classroom+'반':''].filter(Boolean).join(' ');}
function avatar(m,leader=false){return `<div class="avatar" aria-hidden="true">${esc([...m.name][0])}${leader?'<span class="mini-star">✦</span>':''}</div>`;}
function render(){
 document.title=state.teamName+' · 비밀 기록실';$('sideTeam').textContent=state.teamName;$('heroTeam').textContent='팀 '+state.teamName;
 for(const id of ['navCount','sectionCount'])$(id).textContent=state.members.length;$('memberTotal').textContent=String(state.members.length).padStart(2,'0');$('abilityTotal').textContent=String(new Set(state.members.flatMap(m=>m.abilities)).size).padStart(2,'0');renderMembers();renderLeader();updateSaveStatus();
}
function renderMembers(){
 const query=$('searchInput').value.trim().toLocaleLowerCase('ko');const sort=$('sortSelect').value;
 const members=state.members.filter(m=>[m.name,m.school,m.position,...m.abilities,m.id===state.leaderId?'팀장':'팀원'].some(v=>v.toLocaleLowerCase('ko').includes(query))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'ko'):sort==='recent'?Date.parse(b.createdAt)-Date.parse(a.createdAt):Number(b.id===state.leaderId)-Number(a.id===state.leaderId)||Date.parse(a.createdAt)-Date.parse(b.createdAt));
 $('sectionCount').textContent=query?members.length+' / '+state.members.length:state.members.length;
 $('memberGrid').className='member-grid'+(view==='list'?' list':'');
 $('memberGrid').innerHTML=members.map(m=>{const leader=m.id===state.leaderId;const ordinal=String(state.members.findIndex(x=>x.id===m.id)+1).padStart(3,'0');return `<article class="member-card ${leader?'leader':''}">${leader?'<div class="card-ribbon"></div>':''}<div class="card-top">${avatar(m,leader)}<div class="card-name"><h3 title="${esc(m.name)}">${esc(m.name)}</h3><div class="card-id mono">MEMBER · ${ordinal}</div></div><span class="role-badge ${leader?'':'member'}">${leader?'♔ 팀장':'팀원'}</span></div><div class="member-meta">${esc(m.gender||'성별 비공개')}<i>·</i>${m.age?esc(m.age)+'살':'나이 미입력'}${m.birthYear?'<i>·</i>'+esc(m.birthYear.slice(-2))+'년생':''}</div><div class="school">${icon('school')}<div>${esc(m.school||'학교 미입력')}${shortClass(m)?'<br><span class="small" style="font-size:10px;color:#7e957f">'+esc(shortClass(m))+'</span>':''}</div></div><div class="abilities">${m.abilities.length?m.abilities.map((a,i)=>`<span class="ability">${icon(i%3===0?'eye':i%3===1?'seal':'spark')}${esc(a)}</span>`).join(''):'<span class="small muted" style="font-size:10px">발견할 능력이 기다리고 있어요</span>'}</div><div class="card-footer"><span class="mono">${m.position?esc(m.position):'SPIRIT ARCHIVE'}</span><button data-edit="${esc(m.id)}" aria-label="${esc(m.name)} 기록 열기">기록 열기${icon('arrow')}</button></div></article>`;}).join('');
 if(!members.length&&query){$('memberGrid').insertAdjacentHTML('beforeend','<div class="empty">검색 결과가 없어요.<p>이름, 학교 또는 능력을 다시 확인해 보세요.</p><button class="btn btn-outline" id="clearSearch">검색 초기화</button></div>');$('clearSearch').onclick=()=>{$('searchInput').value='';renderMembers();$('searchInput').focus();};}
 else{$('memberGrid').insertAdjacentHTML('beforeend',`<button class="add-card" id="addCard"><span class="plus-circle">${icon('plus')}</span><strong>${state.members.length?'새로운 동료를 기다려요':'첫 번째 동료를 기록해요'}</strong><p>각자의 특별한 능력으로<br>우리 팀을 더 단단하게.</p><span class="link">팀원 등록하기${icon('arrow')}</span></button>`);$('addCard').onclick=()=>openMember();}
 $('memberGrid').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openMember(b.dataset.edit));
}
function renderLeader(){const m=state.members.find(x=>x.id===state.leaderId);$('leaderInfo').innerHTML=m?`<div class="leader-profile">${avatar(m)}<div><strong>${esc(m.name)}</strong><small>팀 ${esc(state.teamName)} · 팀장</small></div></div><dl class="leader-facts"><dt>소속 학교</dt><dd>${esc(m.school||'미입력')}</dd><dt>학년 · 반</dt><dd>${esc(shortClass(m)||'미입력')}</dd><dt>보유 능력</dt><dd>${m.abilities.length?esc(m.abilities.join(' · ')):'아직 미입력'}</dd>${m.position?'<dt>맡은 역할</dt><dd>'+esc(m.position)+'</dd>':''}</dl>`:'<div style="padding:25px 0 6px"><p style="font-size:13px">아직 팀장이 없어요.</p><p class="small muted" style="margin-top:7px">첫 팀원을 등록하면 팀장이 돼요.</p></div>';}

function closeMenu(){$('sidebar').classList.remove('open');$('scrim').classList.remove('show');$('menuButton').setAttribute('aria-expanded','false');}
function openDialog(id){if(!session)return;closeMenu();$(id).showModal();}
function formSignature(){return JSON.stringify([...new FormData($('memberForm')).entries()])+String($('fLeader').checked);}
function openMember(id){if(!session||busy)return;if(!id&&state.members.length>=300){toast('팀원은 최대 300명까지 기록할 수 있어요.',true);return;}editingId=id||null;const m=state.members.find(x=>x.id===id);$('memberForm').reset();$('memberDialog').querySelector('details').open=false;$('memberDialogTitle').textContent=m?'팀원 기록 수정':'새로운 팀원 기록';$('deleteMember').hidden=!m;for(const key of ['name','gender','age','birthYear','school','grade','classroom','position','memo','address'])$('memberForm').elements.namedItem(key).value=m?.[key]??'';$('fAbilities').value=m?.abilities.join(', ')??'';$('fLeader').checked=m?id===state.leaderId:state.members.length===0;$('fLeader').disabled=Boolean(m&&id===state.leaderId)||!state.members.length;openDialog('memberDialog');formSnapshot=formSignature();}
async function closeMemberSafely(){if(busy)return;if(formSignature()!==formSnapshot){if(!(await confirmAction('작성 중인 기록이 있어요','GitHub에 저장하지 않은 입력이 사라져요. 작성을 그만둘까요?','저장하지 않고 닫기')))return;}$('memberDialog').close();}
$('memberForm').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const name=$('fName').value.trim();if(!name){$('fName').setCustomValidity('이름을 입력해 주세요.');$('fName').reportValidity();return;}const abilities=[...new Set($('fAbilities').value.split(/[,，\n]/).map(x=>x.trim()).filter(Boolean))];if(abilities.length>12||abilities.some(x=>x.length>30)){toast('능력은 최대 12개, 각 30자까지 적을 수 있어요.',true);$('fAbilities').focus();return;}const existing=state.members.find(x=>x.id===editingId);const m={id:existing?.id??('member-'+(globalThis.crypto?.randomUUID?.()??Date.now().toString(36)+'-'+Math.random().toString(36).slice(2))),createdAt:existing?.createdAt??new Date().toISOString(),abilities};for(const key of ['name','gender','age','birthYear','school','grade','classroom','position','memo','address'])m[key]=$('memberForm').elements.namedItem(key).value.trim();const candidate=structuredClone(state);if(existing)candidate.members[candidate.members.findIndex(x=>x.id===existing.id)]=m;else candidate.members.push(m);if($('fLeader').checked||!candidate.leaderId)candidate.leaderId=m.id;if(await commit(candidate,existing?'Edit member record':'Add member record')){$('memberDialog').close();toast('팀원 기록을 GitHub에 저장했어요.');}});
$('fName').oninput=()=>$('fName').setCustomValidity('');
$('deleteMember').onclick=async()=>{if(busy)return;const m=state.members.find(x=>x.id===editingId);if(!m)return;const next=state.members.find(x=>x.id!==m.id);let msg=`${m.name} 님의 기록을 현재 팀에서 삭제할까요?\n삭제해도 GitHub의 과거 커밋 이력에는 남아요.`;if(m.id===state.leaderId&&next)msg+=`\n\n${next.name} 님이 새 팀장이 돼요. 나중에 변경할 수 있어요.`;if(await confirmAction('팀원 기록 삭제',msg,'삭제하기',true)){const candidate=structuredClone(state);candidate.members=candidate.members.filter(x=>x.id!==m.id);if(candidate.leaderId===m.id)candidate.leaderId=next?.id??null;if(await commit(candidate,'Remove member record')){$('memberDialog').close();toast('팀원 삭제를 GitHub에 저장했어요.');}}};
$('renameButton').onclick=()=>{$('teamNameInput').value=state.teamName;openDialog('renameDialog');};
$('renameForm').onsubmit=async e=>{e.preventDefault();if(busy)return;const name=$('teamNameInput').value.trim();if(!name){$('teamNameInput').setCustomValidity('팀명을 입력해 주세요.');$('teamNameInput').reportValidity();return;}const candidate=structuredClone(state);candidate.teamName=name;if(await commit(candidate,'Rename team')){$('renameDialog').close();toast('우리 팀의 이름을 GitHub에 저장했어요.');}};$('teamNameInput').oninput=()=>$('teamNameInput').setCustomValidity('');
function openLeader(){if(busy)return;$('leaderOptions').innerHTML=state.members.length?state.members.map(m=>`<button class="leader-option ${m.id===state.leaderId?'selected':''}" data-leader="${esc(m.id)}" aria-label="${esc(m.name)} ${m.id===state.leaderId?'현재 팀장':'팀장으로 선택'}">${avatar(m)}<div><strong>${esc(m.name)}</strong><small>${esc(m.school||'학교 미입력')} ${esc(shortClass(m))}</small></div>${m.id===state.leaderId?'<span class="role-badge">현재 팀장</span>':''}</button>`).join(''):'<div class="empty">아직 등록된 팀원이 없어요.<p>팀원을 먼저 추가해 주세요.</p><button class="btn btn-primary" id="leaderAdd">첫 팀원 추가하기</button></div>';$('leaderOptions').querySelectorAll('[data-leader]').forEach(b=>b.onclick=async()=>{if(busy)return;if(state.leaderId===b.dataset.leader){$('leaderDialog').close();return;}const candidate=structuredClone(state);candidate.leaderId=b.dataset.leader;if(await commit(candidate,'Change team leader')){$('leaderDialog').close();toast('팀장 변경을 GitHub에 저장했어요.');}});if($('leaderAdd'))$('leaderAdd').onclick=()=>{$('leaderDialog').close();openMember();};openDialog('leaderDialog');}
function downloadJson(data,suffix,includeAddresses){const copy=structuredClone(data);copy.exportedAt=new Date().toISOString();if(!includeAddresses)copy.members.forEach(m=>m.address='');const blob=new Blob([JSON.stringify(copy,null,2)],{type:'application/json;charset=utf-8'});const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=copy.teamName.replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_')+'-'+suffix+'-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function openBackup(){if(!session)return;$('lastSavedInfo').textContent=(state.updatedAt?'기록의 마지막 저장 · '+new Date(state.updatedAt).toLocaleString('ko-KR'):'아직 팀원 기록이 없어요.')+' / '+session.config.owner+'/'+session.config.repo;$('githubFileLink').href=githubUrl();openDialog('backupDialog');}
$('exportButton').onclick=()=>{downloadJson(state,'팀기록',$('includeAddresses').checked);toast($('includeAddresses').checked?'기록 사본을 내보냈어요. 개인정보를 소중히 보관해 주세요.':'주소를 제외한 기록 사본을 내보냈어요.');};
$('importButton').onclick=()=>{$('importFile').value='';$('importFile').click();};
$('importFile').onchange=async e=>{if(!session||busy)return;const file=e.target.files[0];if(!file)return;if(file.size>LIMIT){toast('900KB 이하의 기록 파일을 선택해 주세요.',true);return;}let incoming;try{incoming=validate(JSON.parse(await file.text()));}catch(err){toast(err instanceof SyntaxError?'올바른 JSON 백업 파일인지 확인해 주세요.':err.message,true);return;}if(await confirmAction('팀 전체 기록 교체',`‘${incoming.teamName}’ 팀의 기록 ${incoming.members.length}명을 GitHub에 저장할까요?\n\n나뿐 아니라 친구들이 보는 전체 기록이 바뀌어요. 주소도 파일 내용으로 대체돼요. 필요한 기존 기록은 먼저 내보내 주세요.`,'교체하고 저장')){if(await commit(incoming,'Restore team archive from backup')){$('searchInput').value='';render();$('backupDialog').close();toast('백업 기록을 GitHub에 저장했어요.');}}};
async function refresh(silent=false){if(!session||busy||polling)return;if(silent&&(pendingDraft||document.querySelector('dialog[open]')||document.hidden||Date.now()<pollAfter))return;const auth=session,requestEpoch=epoch,shaAtStart=session.sha;polling=true;try{const remote=await readRemote(auth);if(epoch!==requestEpoch||session!==auth||session.sha!==shaAtStart)return;if(busy||(!silent&&document.querySelector('dialog[open]'))||pendingDraft)return;if(remote.sha!==session.sha){if(document.querySelector('dialog[open]'))return;state=remote.state;session.sha=remote.sha;render();if(silent)toast('친구가 저장한 최신 기록을 불러왔어요.');}lastCheck=Date.now();syncError='';if(!silent)toast('GitHub의 최신 기록을 확인했어요.');}catch(e){if(epoch===requestEpoch){syncError=explain(e);if(!silent)toast(syncError,true);}}finally{polling=false;updateSaveStatus();}}
async function restoreLatest(){if(!session||busy)return;if(!(await confirmAction('최신 기록으로 돌아가기','저장하지 않은 변경과 열려 있는 편집 입력을 버리고 GitHub의 최신 기록을 불러올까요? 필요한 내용은 먼저 파일로 보관해 주세요.','최신 기록 불러오기')))return;const auth=session,requestEpoch=epoch;setBusy(true);try{const remote=await readRemote(auth);if(epoch!==requestEpoch)return;state=remote.state;session.sha=remote.sha;pendingDraft=null;syncError='';lastCheck=Date.now();document.querySelectorAll('dialog[open]').forEach(d=>d.close());$('memberForm').reset();render();toast('최신 기록을 불러왔어요. 필요한 변경을 다시 적용해 주세요.');}catch(e){showIssue(explain(e));}finally{setBusy(false);}}
$('downloadDraft').onclick=()=>{if(pendingDraft){downloadJson(pendingDraft,'미저장초안',false);toast('주소를 제외한 미저장 변경을 파일로 보관했어요. 전체 기록을 덮어쓰는 복원 대신 필요한 내용만 다시 적용해 주세요.');}};
$('retryDraft').onclick=async()=>{if(!pendingDraft||busy)return;if(await commit(pendingDraft,'Retry team archive update')){document.querySelectorAll('dialog[open]').forEach(d=>d.close());toast('변경사항을 GitHub에 저장했어요.');}};
$('issueRefresh').onclick=restoreLatest;
$('refreshButton').onclick=()=>pendingDraft?showIssue():refresh();$('saveState').onclick=()=>pendingDraft?showIssue():refresh();
function activate(remote){state=remote.state;session.sha=remote.sha;lastCheck=Date.now();syncError='';pendingDraft=null;$('loginScreen').hidden=true;$('sidebar').hidden=false;$('appMain').hidden=false;$('searchInput').value='';$('accessToken').value='';document.querySelector('meta[name="theme-color"]').content='#101614';render();window.scrollTo(0,0);toast('비공개 GitHub 기록실에 연결했어요.');}
$('loginForm').onsubmit=async e=>{e.preventDefault();if(busy)return;$('loginError').hidden=true;let c,token;try{c=connection();token=$('accessToken').value.trim();if(!/^github_pat_[A-Za-z0-9_]{20,}$/.test(token))throw new Error('Fine-grained 개인 접근 토큰(github_pat_로 시작)을 입력해 주세요. GitHub 비밀번호나 공통 토큰은 사용하지 않아요.');}catch(err){$('loginError').textContent=err.message;$('loginError').hidden=false;return;}epoch++;const attempt=epoch;session={config:c,token,sha:null};token='';$('accessToken').value='';$('accessToken').type='password';$('toggleToken').setAttribute('aria-pressed','false');$('toggleToken').setAttribute('aria-label','토큰 보기');setBusy(true);$('connectButton').querySelector('span').textContent='GitHub 권한 확인 중…';try{const repo=await api(base());if(!repo.private)throw new Error('개인정보 보호를 위해 비공개(Private) 기록 저장소만 연결할 수 있어요. 화면용 공개 저장소와 기록용 비공개 저장소를 분리해 주세요.');await api(base()+'/branches/'+encodeURIComponent(c.branch));let remote;try{remote=await readRemote();}catch(err){if(err.status!==404)throw err;setBusy(false);const yes=await confirmAction('첫 기록실 만들기',`${c.owner}/${c.repo}의 ${c.path} 파일이 아직 없어요.\n\n이 비공개 저장소에 팀명 ‘퇴마사’, 팀원 0명의 새 기록실을 만들까요?`,'빈 기록실 만들기');if(!yes)throw new Error('기록실 생성을 취소했어요. 기존 파일 경로가 있다면 연결 경로를 확인해 주세요.');setBusy(true);const first=structuredClone(EMPTY);first.updatedAt=new Date().toISOString();const result=await api(contentsPath(),{method:'PUT',body:{message:'Initialize private team archive',content:encodeJson(first),branch:c.branch}});if(!result.content?.sha)throw new Error('파일 생성 결과를 확인하지 못했어요. 다시 연결해 주세요.');remote={state:first,sha:result.content.sha};}if(attempt===epoch)activate(remote);}catch(err){if(attempt===epoch){session=null;state=structuredClone(EMPTY);$('loginError').textContent=explain(err)+'\n토큰은 저장하지 않으므로 다시 입력해 주세요.';$('loginError').hidden=false;}}finally{setBusy(false);$('connectButton').querySelector('span').textContent='기록실 연결하기';}};
function wipeSession(){epoch++;requests.forEach(c=>c.abort());session=null;state=structuredClone(EMPTY);pendingDraft=null;lastCheck=null;syncError='';lastIssue='';editingId=null;formSnapshot='';lastCheck=null;pollAfter=0;closeMenu();if(confirmResolver)finishConfirm(false);document.querySelectorAll('dialog[open]').forEach(d=>d.close());for(const id of ['memberGrid','leaderInfo','leaderOptions'])$(id).replaceChildren();$('memberForm').reset();$('renameForm').reset();$('importFile').value='';$('includeAddresses').checked=false;$('issueMessage').textContent='';$('confirmMessage').textContent='';$('lastSavedInfo').textContent='';$('githubFileLink').href='https://github.com';$('toasts').replaceChildren();$('loginError').hidden=true;$('accessToken').value='';$('searchInput').value='';$('sideTeam').textContent='연결 대기';$('heroTeam').textContent='우리 팀';document.title='비밀 기록실 · GitHub 공동 기록';$('sidebar').hidden=true;$('appMain').hidden=true;$('loginScreen').hidden=false;window.scrollTo(0,0);$('accessToken').focus();}
$('logoutButton').onclick=async()=>{if(busy)return;if(pendingDraft&&!(await confirmAction('로그아웃할까요?','GitHub에 저장하지 않은 변경사항이 사라져요. 필요한 초안은 먼저 파일로 보관해 주세요.','로그아웃')))return;wipeSession();toast('이 페이지의 연결과 기록을 비웠어요. GitHub 사이트의 로그인은 별도예요.');};
$('toggleToken').onclick=()=>{const show=$('accessToken').type==='password';$('accessToken').type=show?'text':'password';$('toggleToken').setAttribute('aria-pressed',String(show));$('toggleToken').setAttribute('aria-label',show?'토큰 숨기기':'토큰 보기');};
$('navMembers').onclick=()=>{closeMenu();$('memberSection').scrollIntoView({behavior:'smooth',block:'start'});};$('navLeader').onclick=openLeader;$('changeLeader').onclick=openLeader;$('navBackup').onclick=openBackup;$('noteBackup').onclick=openBackup;$('navGuide').onclick=()=>openDialog('guideDialog');$('addButton').onclick=()=>openMember();$('searchInput').oninput=renderMembers;$('sortSelect').onchange=renderMembers;
function setView(mode){view=mode;for(const v of ['grid','list']){$(v+'View').classList.toggle('active',v===mode);$(v+'View').setAttribute('aria-pressed',String(v===mode));}renderMembers();}$('gridView').onclick=()=>setView('grid');$('listView').onclick=()=>setView('list');
$('menuButton').onclick=()=>{const open=$('sidebar').classList.toggle('open');$('scrim').classList.toggle('show',open);$('menuButton').setAttribute('aria-expanded',String(open));};$('scrim').onclick=closeMenu;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(busy)return;b.dataset.close==='memberDialog'?closeMemberSafely():$(b.dataset.close).close();});document.querySelectorAll('dialog').forEach(d=>d.addEventListener('cancel',e=>{if(busy)e.preventDefault();}));$('memberDialog').addEventListener('cancel',e=>{e.preventDefault();if(!busy)closeMemberSafely();});
window.addEventListener('beforeunload',e=>{if(busy||pendingDraft||($('memberDialog').open&&formSignature()!==formSnapshot)||($('renameDialog').open&&$('teamNameInput').value.trim()!==state.teamName)){e.preventDefault();e.returnValue='';}});
// Prevent sensitive DOM/session restoration through the back-forward cache.
window.addEventListener('pagehide',()=>{if(session)wipeSession();});
setInterval(()=>refresh(true),POLL_MS);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true);});
for(const [key,id]of [['owner','repoOwner'],['repo','repoName'],['branch','repoBranch'],['path','repoPath']])$(id).value=String(config[key]||'');
if(config.owner&&config.repo){$('repoFields').hidden=true;$('repoSummary').hidden=false;$('configuredRepo').textContent=config.owner+'/'+config.repo;for(const id of ['repoOwner','repoName','repoBranch','repoPath'])$(id).readOnly=true;}
const now=new Date();$('today').append(document.createTextNode(new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit'}).format(now).replaceAll('-',' . ')));const dateSub=document.createElement('span');dateSub.textContent='CONNECTED BY COURAGE';$('today').append(dateSub);

