const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
const TOKEN='github_pat_'+('a'.repeat(45));const READONLY='github_pat_'+('r'.repeat(45));const BAD='github_pat_'+('z'.repeat(45));
let data={version:1,teamName:'퇴마사',leaderId:null,updatedAt:null,members:[]},sha='initial-sha',revision=0,exists=true,privateRepo=true,broken=false,putCount=0,apiCount=0,lastPut=null;
const errors=[];const cors={'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'GET, PUT, OPTIONS','access-control-expose-headers':'x-ratelimit-remaining'};
async function routeApi(route){const req=route.request(),url=new URL(req.url());apiCount++;const auth=req.headers()['authorization'];const reply=(status,body)=>route.fulfill({status,contentType:'application/json',headers:cors,body:JSON.stringify(body)});if(req.method()==='OPTIONS')return reply(200,{});if(auth==='Bearer '+BAD)return reply(401,{message:'Bad credentials'});if(![TOKEN,READONLY].some(t=>auth==='Bearer '+t))return reply(401,{});
 if(url.pathname==='/repos/test-org/spirit-data')return reply(200,{private:privateRepo,permissions:{push:auth==='Bearer '+TOKEN}});
 if(url.pathname==='/repos/test-org/spirit-data/branches/main')return reply(200,{name:'main'});
 if(url.pathname==='/repos/test-org/spirit-data/contents/data/team.json'){
  if(req.method()==='GET'){if(!exists)return reply(404,{});return reply(200,{type:'file',encoding:'base64',sha,size:Buffer.byteLength(JSON.stringify(data)),content:Buffer.from(broken?'INVALID JSON':JSON.stringify(data)).toString('base64')});}
  if(req.method()==='PUT'){putCount++;if(auth==='Bearer '+READONLY)return reply(403,{});const body=req.postDataJSON();lastPut=body;if((exists&&body.sha!==sha)||(!exists&&body.sha))return reply(409,{message:'sha does not match'});data=JSON.parse(Buffer.from(body.content,'base64').toString());sha='sha-'+(++revision);exists=true;return reply(200,{content:{sha},commit:{sha:'commit-'+revision}});}
 }return reply(404,{});
}
async function ready(p){await p.route('https://api.github.com/**',routeApi);p.on('pageerror',e=>errors.push(e.message));p.on('console',msg=>{if(msg.type()==='error'&&msg.text().includes('Content Security'))errors.push(msg.text());});await p.goto('http://127.0.0.1:3000');}
async function connect(p,token=TOKEN){await p.fill('#repoOwner','test-org');await p.fill('#repoName','spirit-data');await p.fill('#accessToken',token);await p.click('#connectButton');}
async function waitApp(p){await p.locator('#appMain').waitFor({state:'visible'});}
async function rename(p,name){await p.click('#renameButton');await p.fill('#teamNameInput',name);await p.locator('#renameForm button[type=submit]').click();}
async function add(p,name,ability='결계, 퇴마'){await p.click('#addButton');await p.fill('#fName',name);await p.fill('#fAge','14');await p.fill('#fBirth','2012');await p.fill('#fSchool','가상학교');await p.fill('#fGrade','2');await p.fill('#fClass','1');await p.fill('#fAbilities',ability);await p.fill('#fMemo','테스트 메모');await p.locator('#memberForm button[type=submit]').click();await p.locator('#memberDialog').waitFor({state:'hidden'});}
(async()=>{const b=await chromium.launch({headless:true});const p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});await ready(p);assert.equal(apiCount,0);assert.equal(await p.locator('#appMain').isVisible(),false);assert(!(await p.content()).includes('안태은'));await p.screenshot({path:'/home/user/spirit-github/tests/login-desktop.png',fullPage:true});
 await connect(p,BAD);await p.locator('#loginError').waitFor({state:'visible'});assert((await p.textContent('#loginError')).includes('토큰'));assert.equal(await p.locator('#appMain').isVisible(),false);
 privateRepo=false;await connect(p);await p.locator('#loginError').waitFor({state:'visible'});assert((await p.textContent('#loginError')).includes('비공개'));privateRepo=true;
 exists=false;await connect(p);await p.locator('#confirmDialog').waitFor({state:'visible'});await p.click('#confirmOkay');await waitApp(p);assert(exists);assert.equal(data.teamName,'퇴마사');assert.equal(data.members.length,0);assert.equal(await p.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.equal(await p.inputValue('#accessToken'),'');
 const q=await b.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'});await ready(q);await connect(q);await waitApp(q);
 await add(p,'별빛');assert.equal(data.members.length,1);assert.equal(data.leaderId,data.members[0].id);assert.equal(data.members[0].memo,'테스트 메모');assert.equal(lastPut.branch,'main');
 await q.click('#refreshButton');await q.waitForFunction(()=>document.querySelectorAll('.member-card').length===1);assert((await q.textContent('#memberGrid')).includes('별빛'));
 await p.click('#renameButton');await p.fill('#teamNameInput','내가 바꾼 팀');await rename(q,'친구가 바꾼 팀');await q.locator('#renameDialog').waitFor({state:'hidden'});assert.equal(data.teamName,'친구가 바꾼 팀');await p.locator('#renameForm button[type=submit]').click();await p.locator('#issueDialog').waitFor({state:'visible'});assert.equal(data.teamName,'친구가 바꾼 팀');assert((await p.textContent('#saveLabel')).includes('미저장'));
 const download=p.waitForEvent('download');await p.click('#downloadDraft');const d=await download;const draft=JSON.parse(fs.readFileSync(await d.path(),'utf8'));assert.equal(draft.teamName,'내가 바꾼 팀');assert(draft.members.every(m=>!m.address));await p.click('#issueRefresh');await p.click('#confirmOkay');await p.locator('#issueDialog').waitFor({state:'hidden'});assert.equal(await p.textContent('#sideTeam'),'친구가 바꾼 팀');
 await add(p,'달빛','예지, 예지, 귀신 봄');assert.equal(data.members.length,2);assert.equal(data.members[1].abilities.length,2);await p.click('#changeLeader');await p.locator('[data-leader]').filter({hasText:'달빛'}).click();await p.locator('#leaderDialog').waitFor({state:'hidden'});assert.equal(data.leaderId,data.members[1].id);
 await p.locator('.member-card.leader [data-edit]').click();await p.fill('#fMemo','수정 메모');await p.locator('#memberDialog summary').click();await p.fill('#fAddress','가상 기지');await p.locator('#memberForm button[type=submit]').click();await p.locator('#memberDialog').waitFor({state:'hidden'});assert.equal(data.members[1].memo,'수정 메모');assert.equal(data.members[1].address,'가상 기지');
 await p.fill('#searchInput','예지');assert.equal(await p.locator('.member-card').count(),1);await p.fill('#searchInput','존재하지않음');assert.equal(await p.locator('.member-card').count(),0);await p.click('#clearSearch');await p.click('#listView');assert((await p.getAttribute('#memberGrid','class')).includes('list'));await p.click('#gridView');
 await p.click('#navBackup');let download2=p.waitForEvent('download');await p.click('#exportButton');const d2=await download2;const backup=JSON.parse(fs.readFileSync(await d2.path(),'utf8'));assert(backup.members.every(m=>!m.address));await p.setInputFiles('#importFile',{name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{oops')});assert(await p.locator('#backupDialog').isVisible());const xss=structuredClone(backup);xss.teamName='안전한 테스트';xss.members[1].name='<img src=x onerror=alert(1)>';await p.setInputFiles('#importFile',{name:'safe.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(xss))});await p.click('#confirmOkay');await p.locator('#backupDialog').waitFor({state:'hidden'});assert.equal(await p.locator('#memberGrid img').count(),0);assert.equal(data.teamName,'안전한 테스트');
 await p.locator('.member-card.leader [data-edit]').click();await p.click('#deleteMember');await p.click('#confirmOkay');await p.locator('#memberDialog').waitFor({state:'hidden'});assert.equal(data.members.length,1);assert.equal(data.leaderId,data.members[0].id);
 await p.locator('[data-edit]').click();await p.fill('#fName','미저장 입력');await p.locator('#memberDialog [data-close]').first().click();await p.locator('#confirmDialog').waitFor({state:'visible'});await p.click('#confirmCancel');assert(await p.locator('#memberDialog').isVisible());await p.locator('#memberForm button[type=submit]').click();await p.locator('#memberDialog').waitFor({state:'hidden'});
 const readonly=await b.newPage({reducedMotion:'reduce'});await ready(readonly);await connect(readonly,READONLY);await waitApp(readonly);const before=data.teamName;await rename(readonly,'금지된 수정');await readonly.locator('#issueDialog').waitFor({state:'visible'});assert.equal(data.teamName,before);assert((await readonly.textContent('#issueMessage')).includes('권한'));await readonly.locator('#issueDialog [data-close]').first().click();await readonly.locator('#renameDialog [data-close]').first().click();await readonly.click('#logoutButton');await readonly.click('#confirmOkay');await readonly.locator('#loginScreen').waitFor({state:'visible'});assert.equal(await readonly.locator('.member-card').count(),0);assert.equal(await readonly.evaluate(()=>localStorage.length+sessionStorage.length),0);assert(!(await readonly.locator('body').innerText()).includes('미저장 입력'));
 broken=true;const oldTitle=await p.textContent('#sideTeam');await p.click('#refreshButton');await p.waitForFunction(()=>document.querySelector('#saveLabel').textContent==='최신 확인 필요');assert.equal(await p.textContent('#sideTeam'),oldTitle);broken=false;
 await p.screenshot({path:'/home/user/spirit-github/tests/app-desktop.png',fullPage:true});await p.reload();assert.equal(await p.locator('#appMain').isVisible(),false);assert.equal(await p.locator('.member-card').count(),0);assert.equal(await p.inputValue('#accessToken'),'');
 await p.setViewportSize({width:390,height:844});await p.screenshot({path:'/home/user/spirit-github/tests/login-mobile.png',fullPage:true});for(const width of [320,390,768,1024,1440]){await p.setViewportSize({width,height:900});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 // Auto refresh path, without waiting for a real timer.
 await q.evaluate(()=>refresh(true));await q.waitForFunction(()=>document.querySelector('#sideTeam').textContent==='안전한 테스트');assert.equal(await q.locator('.member-card').count(),1);
 // The source does not store secrets or make external non-GitHub calls.
 assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: auth gate, private-only, initial creation, Unicode CRUD, 2-client sync, SHA conflict, backup, restore, draft, XSS escaping, readonly rejection, corrupt JSON, logout, refresh reset, responsive layout.');console.log('Mock API calls:',apiCount,'PUT attempts:',putCount,'Runtime/CSP errors:',errors.length);await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
